Get-ADUser -Identity "#abarra" -Properties AccountNotDelegated
Get-ADUser -Identity "#asanchezc" -Properties AccountNotDelegated
Get-ADUser -Identity "#aulloaf" -Properties AccountNotDelegated
Get-ADUser -Identity "#blatorre" -Properties AccountNotDelegated
Get-ADUser -Identity "#bsanchez" -Properties AccountNotDelegated
Get-ADUser -Identity "#bserey" -Properties AccountNotDelegated
Get-ADUser -Identity "#cgatica" -Properties AccountNotDelegated
Get-ADUser -Identity "#cramirezc" -Properties AccountNotDelegated
Get-ADUser -Identity "#dcares" -Properties AccountNotDelegated
Get-ADUser -Identity "#dojeda" -Properties AccountNotDelegated
Get-ADUser -Identity "#igieminiani" -Properties AccountNotDelegated
Get-ADUser -Identity "#igodoy" -Properties AccountNotDelegated
Get-ADUser -Identity "#iserrano" -Properties AccountNotDelegated
Get-ADUser -Identity "#jquezada" -Properties AccountNotDelegated
Get-ADUser -Identity "#jupena" -Properties AccountNotDelegated
Get-ADUser -Identity "#kvalenzuela" -Properties AccountNotDelegated
Get-ADUser -Identity "#lsanchez" -Properties AccountNotDelegated
Get-ADUser -Identity "#mortiz" -Properties AccountNotDelegated
Get-ADUser -Identity "#mosorio" -Properties AccountNotDelegated
Get-ADUser -Identity "#ohenriquez" -Properties AccountNotDelegated
Get-ADUser -Identity "#ozarria" -Properties AccountNotDelegated
Get-ADUser -Identity "#plezaeta" -Properties AccountNotDelegated
Get-ADUser -Identity "#rrosales" -Properties AccountNotDelegated



Set-ADAccountControl -Identity "#abarra" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#asanchezc" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#aulloaf" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#blatorre" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#bsanchez" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#bserey" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#cgatica" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#cramirezc" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#dcares" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#dojeda" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#igieminiani" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#igodoy" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#iserrano" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#jquezada" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#jupena" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#kvalenzuela" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#lsanchez" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#mortiz" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#mosorio" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#ohenriquez" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#ozarria" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#plezaeta" -AccountNotDelegated $True
Set-ADAccountControl -Identity "#rrosales" -AccountNotDelegated $True

